import type { Metadata } from 'next';
import Link from '@/i18n/navigation';
import { notFound } from 'next/navigation';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { ALL_TOOLS, hasVerifiedScore, computeOverall } from '@/data/tools';
import { localizeTools, getLocalizedField, localizedCategoryLabel } from '@/lib/i18n/content';
import { byRankDesc } from '@/lib/ranking';
import { GRAVEYARD } from '@/data/graveyard';
import { SITE_URL, SITE_NAME, MIN_REVIEWS_FOR_AGGREGATE_RATING } from '@/config/site';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ToolCard } from '@/components/ToolCard';
import { CompareBar } from '@/components/CompareBar';
import { ReviewSection } from '@/components/ReviewSection';
import { ToolActions } from '@/components/ToolActions';
import { ShareButtons } from '@/components/ShareButtons';
import { HelpfulFeedback } from '@/components/HelpfulFeedback';
import { EvidenceCard } from '@/components/EvidenceCard';
import { ScoreBreakdown } from '@/components/ScoreBreakdown';
import { PricingPlansSection } from '@/components/PricingPlansSection';
import { VerificationBadge, NotTestedNotice } from '@/components/VerificationBadge';
import { SmartImage } from '@/components/SmartImage';
import { CoverArt } from '@/components/CoverArt';
import { PriceHistorySection } from '@/components/PriceHistorySection';
import { StudioContextualCTA } from '@/components/StudioContextualCTA';
import { getApprovedReviewStats } from '@/lib/reviewStats';
import { TOOL_DEEP_DIVES } from '@/data/tool-deep-dives';
import { buildToolFaq } from '@/lib/toolFaq';
import {
  ExternalLink,
  ArrowLeft,
  CalendarCheck,
  Tag,
  DollarSign,
  Award,
} from 'lucide-react';

export const dynamicParams = false;

export function generateStaticParams() {
  return ALL_TOOLS.map((t) => ({ slug: t.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string; locale: string }>;
}): Promise<Metadata> {
  const { slug, locale } = await params;
  const t = await getTranslations({ locale, namespace: 'tool' });
  const tool = ALL_TOOLS.find((x) => x.slug === slug);
  if (!tool) return { title: t('notFoundTitle') };

  const tested = hasVerifiedScore(tool);

  /**
   * Audit fix 1.1 — the old title promised "Review 2026" for 153 tools that
   * had never been reviewed. Titles now match what the page actually contains.
   * Critique §7 fix — titles are also differentiated per tool instead of one
   * repeated pattern: category and pricing context go in.
   */
  const title = tested
    ? t('metaTested', { name: tool.name })
    : tool.pricing === 'Free'
      ? t('metaFree', { name: tool.name, category: tool.category })
      : t('metaPaid', { name: tool.name, category: tool.category });

  const description = tested
    ? t('metaTestedDesc', {
        name: tool.name,
        tagline: tool.tagline,
        score: computeOverall(tool.scores!).toFixed(1),
        price: tool.startingPrice ?? t('free'),
      })
    : t('metaListedDesc', {
        name: tool.name,
        intro: tool.pageIntro ?? tool.tagline,
        body: tool.longDescription ?? tool.description,
        pricing: tool.pricing,
        price: tool.startingPrice ? ` from ${tool.startingPrice}` : '',
        category: tool.category,
      });

  return {
    title,
    description,
    alternates: { canonical: `/tool/${tool.slug}` },
    openGraph: {
      title,
      description,
      url: `/tool/${tool.slug}`,
      type: 'article',
      // Dynamic OG image (audit fix 3.2) is generated by opengraph-image.tsx.
    },
    twitter: { card: 'summary_large_image', title, description },
  };
}

function priceNumber(s?: string): string | undefined {
  const m = s?.match(/[\d.]+/);
  return m ? m[0] : undefined;
}

export default async function ToolDetailPage({
  params,
}: {
  params: Promise<{ slug: string; locale: string }>;
}) {
  const { slug, locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations({ locale, namespace: 'tool' });
  const tcommon = await getTranslations({ locale, namespace: 'common' });
  const tc = await getTranslations({ locale, namespace: 'categories' });
  const found = ALL_TOOLS.find((x) => x.slug === slug);
  if (!found) notFound();
  const [tool] = await localizeTools([found], locale);
  const pricingLabel = (p: string) =>
    p === 'Free Trial' ? tcommon('freeTrial') : tcommon(p.toLowerCase() as never);

  const tested = hasVerifiedScore(tool);
  const overall = tested && tool.scores ? computeOverall(tool.scores) : null;

  /**
   * Audit fix 1.2 — real approved review counts, read at build time.
   * The old code emitted ratingCount: Math.max(tool.reviewsCount, 1), which
   * told Google "1 person rated this 4.8" for 153 tools with zero reviews.
   * That is textbook structured-data spam.
   */
  const reviewStats = await getApprovedReviewStats(tool.slug);

  const alternatives = ALL_TOOLS.filter((t) => t.slug !== tool.slug && t.category === tool.category)
    .sort(byRankDesc)
    .slice(0, 4);

  const related = ALL_TOOLS.filter(
    (t) =>
      t.slug !== tool.slug &&
      t.category !== tool.category &&
      t.tags.some((tag) => tool.tags.includes(tag))
  ).slice(0, 4);

  // Dead tools that this one replaces — turns the graveyard into inbound links.
  const replaces = GRAVEYARD.filter((d) => d.replacements.includes(tool.slug));

  /**
   * Critique §4/§5/§7 — deep-dive content + honest generated FAQ.
   * Deep dives are hand-written only for flagship tools (tool-deep-dives.ts);
   * every tool gets the data-derived FAQ, which renders visibly AND feeds a
   * FAQPage rich-result. Nothing here can claim a test that did not happen.
   */
  const diveRaw = TOOL_DEEP_DIVES[tool.slug];
  // i18n: deep-dive content is translated by the engine (entity deepDive).
  const lOverview = await getLocalizedField('deepDive', tool.slug, 'overview', locale);
  const lUseCases = await getLocalizedField('deepDive', tool.slug, 'useCases', locale);
  const lBestFor = await getLocalizedField('deepDive', tool.slug, 'bestFor', locale);
  const lAvoidIf = await getLocalizedField('deepDive', tool.slug, 'avoidIf', locale);
  const lPricingNotes = await getLocalizedField('deepDive', tool.slug, 'pricingNotes', locale);
  const dive = diveRaw
    ? {
        overview: lOverview ? lOverview.split('\n').filter(Boolean) : diveRaw.overview,
        useCases: lUseCases ? lUseCases.split('\n').filter(Boolean) : diveRaw.useCases,
        bestFor: lBestFor ? lBestFor.split('\n').filter(Boolean) : diveRaw.bestFor,
        avoidIf: lAvoidIf ? lAvoidIf.split('\n').filter(Boolean) : diveRaw.avoidIf,
        pricingNotes: lPricingNotes ?? diveRaw.pricingNotes,
        faqs: diveRaw.faqs ?? [],
      }
    : undefined;
  const faqs = buildToolFaq(tool, alternatives.map((a) => a.name), dive?.faqs ?? []);

  const jsonLd: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: tool.name,
    description: tool.description,
    url: tool.url,
    applicationCategory: 'MultimediaApplication',
    operatingSystem: 'Web',
    offers: {
      '@type': 'Offer',
      price: priceNumber(tool.startingPrice) || '0',
      priceCurrency: 'USD',
      description: tool.pricing,
      ...(tool.pricingSourceUrl && { url: tool.pricingSourceUrl }),
    },
  };

  // aggregateRating ONLY with enough genuine approved reviews (audit fix 1.2).
  if (reviewStats.count >= MIN_REVIEWS_FOR_AGGREGATE_RATING) {
    jsonLd.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: reviewStats.average,
      bestRating: 5,
      worstRating: 1,
      ratingCount: reviewStats.count,
    };
  }

  // A single editorial Review is always legitimate — but only when we tested it.
  if (tested && overall !== null) {
    jsonLd.review = {
      '@type': 'Review',
      author: { '@type': 'Organization', name: `${SITE_NAME} Editorial Team` },
      datePublished: tool.testedAt,
      reviewRating: {
        '@type': 'Rating',
        ratingValue: Math.round((overall / 2) * 10) / 10, // 0–10 → 0–5
        bestRating: 5,
        worstRating: 1,
      },
      reviewBody: tool.verdict?.bestFor ?? tool.description,
    };
  }

  /** Critique §7 — FAQ structured data for rich results (all answers honest by construction). */
  const faqLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };

  const breadcrumbLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
      { '@type': 'ListItem', position: 2, name: 'All Tools', item: `${SITE_URL}/tools` },
      {
        '@type': 'ListItem',
        position: 3,
        name: tool.category,
        item: `${SITE_URL}/category/${encodeURIComponent(
          tool.category.toLowerCase().replace(/[^a-z0-9]+/g, '-')
        )}`,
      },
      { '@type': 'ListItem', position: 4, name: tool.name, item: `${SITE_URL}/tool/${tool.slug}` },
    ],
  };

  return (
    <div className="min-h-screen bg-surface-0 text-foreground">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }}
      />
      <Header />

      <main id="main" className="mx-auto max-w-5xl px-4 py-10">
        <Link
          href="/tools"
          className="mb-6 inline-flex items-center gap-1.5 text-2xs font-semibold text-zinc-400 transition-colors hover:text-accent-400"
        >
          <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" /> Back to All Tools
        </Link>

        {/* Hero — v2.6: generated brand cover (stock imagery removed) */}
        <div className="relative overflow-hidden rounded-3xl border border-white/10">
          <div className="relative h-56 sm:h-72">
            <CoverArt
              slug={tool.slug}
              title={tool.name}
              logo={tool.logo}
              logoSize={72}
              className="absolute inset-0"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-surface-0 via-black/50 to-transparent" />
          </div>
          <div className="relative -mt-16 px-6 pb-6 sm:px-8">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-end">
              <SmartImage
                src={tool.logo}
                alt={`${tool.name} logo`}
                width={80}
                height={80}
                className="h-20 w-20 rounded-2xl border border-white/10 bg-surface-2 object-cover shadow-2xl"
              />
              <div className="flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <h1 className="text-3xl font-black tracking-tight">{tool.name}</h1>
                  {tool.isEditorsChoice && tested && (
                    <span className="inline-flex items-center gap-1 rounded-full bg-accent-500 px-2.5 py-1 text-2xs font-bold text-black">
                      <Award className="h-3 w-3" aria-hidden="true" /> {tcommon('editorsChoice')}
                    </span>
                  )}
                  {/* The fabricated `isTrending` badge was removed: "Trending"
                      is a popularity claim we cannot back up with source. */}
                </div>
                <p className="mt-1 text-sm text-zinc-300">{tool.tagline}</p>
                <div className="mt-2">
                  <VerificationBadge
                    level={tool.verificationLevel}
                    testedAt={tool.testedAt}
                  />
                </div>
              </div>
              <div className="flex items-center gap-2">
                <ToolActions slug={tool.slug} name={tool.name} />
                <a
                  href={`/go/${tool.slug}`}
                  target="_blank"
                  rel={
                    tool.affiliateProgram
                      ? 'noopener noreferrer nofollow sponsored'
                      : 'noopener noreferrer nofollow'
                  }
                  className="inline-flex items-center gap-2 rounded-2xl bg-accent-500 px-6 py-3 text-sm font-bold text-black shadow-lg shadow-accent-500/20 transition-opacity hover:opacity-90"
                >
                  {t('visitSite')} {tool.name} <ExternalLink className="h-4 w-4" aria-hidden="true" />
                </a>
              </div>
            </div>
          </div>
        </div>

        {/* Quick facts */}
        <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <Award className="h-3 w-3" aria-hidden="true" /> {t('ourScore')}
            </div>
            {/* Audit fix 2.1 — no invented number when we have not tested it. */}
            {overall !== null ? (
              <div className="mt-1 flex items-baseline gap-1">
                <span className="font-mono text-xl font-black tabular-nums text-white">
                  {overall.toFixed(1)}
                </span>
                <span className="text-2xs text-zinc-500">/ 10</span>
              </div>
            ) : (
              <div className="mt-1 text-sm font-semibold text-zinc-500">{t('notYetTested')}</div>
            )}
          </div>

          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
                <DollarSign className="h-3 w-3" aria-hidden="true" /> {t('pricingTitle')}
              </div>
              {tool.verificationLevel === 'pricing-verified' && (
                <VerificationBadge level={tool.verificationLevel} compact />
              )}
            </div>
            <div className="mt-1 text-sm font-bold text-emerald-400">
              {pricingLabel(tool.pricing)}
              {tool.startingPrice ? ` · ${tool.startingPrice}` : ''}
            </div>
            {/* Audit fix 2.3 — price claims now cite a source and a date. */}
            {tool.pricingSourceUrl && tool.pricingCheckedAt && (
              <a
                href={tool.pricingSourceUrl}
                target="_blank"
                rel="noopener noreferrer nofollow"
                className="mt-1 block text-2xs text-zinc-500 underline hover:text-zinc-300"
              >
                {t('sourceChecked', { date: tool.pricingCheckedAt })}
              </a>
            )}
          </div>

          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <Tag className="h-3 w-3" aria-hidden="true" /> {t('categoryLabel')}
            </div>
            <Link
              href={`/tools?category=${encodeURIComponent(tool.category)}`}
              className="mt-1 block text-sm font-bold text-white hover:text-accent-300"
            >
              {tc.has(tool.category) ? tc(tool.category) : tool.category}
            </Link>
          </div>

          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <CalendarCheck className="h-3 w-3" aria-hidden="true" />
              {tested ? t('testedOnShort') : t('listedOnly')}
            </div>
            <div className="mt-1 text-sm font-bold text-white">
              {tested ? (
                <span className="font-mono tabular-nums">{tool.testedAt}</span>
              ) : tool.pricingCheckedAt ? (
                <span className="font-mono tabular-nums">{tool.pricingCheckedAt}</span>
              ) : (
                // Better than a bare dash: says what the state actually is.
                <span className="text-zinc-500">{t('inCatalog')}</span>
              )}
            </div>
          </div>
        </div>

        {/*
          Audit fix 1.1 — the Evidence Card is now conditional. Previously an
          identical hardcoded card claiming "Hands-on + Vendor Data" appeared
          on all 200 pages, including 153 machine-generated entries.
        */}
        {tested ? <EvidenceCard tool={tool} /> : <NotTestedNotice toolName={tool.name} />}

        {/* Price-check evidence: parsed plans + official source + note. */}
        {tool.verificationLevel === 'pricing-verified' && <PricingPlansSection tool={tool} />}

        {/* A contextual handoff only — this does not rank or recommend the current external tool. */}
        <StudioContextualCTA category={tool.category} />

        {/* Critique §11-7 — price history chart for source-checked tools. */}
        {tool.verificationLevel !== 'listed-only' && (
          <PriceHistorySection
            slug={tool.slug}
            currentPrice={tool.startingPrice}
            checkedAt={tool.pricingCheckedAt}
          />
        )}

        {tested && tool.scores && <ScoreBreakdown scores={tool.scores} verdict={tool.verdict} />}

        {/* Pros & cons — audit fix 2.1: no tool previously listed a drawback. */}
        {(tool.pros?.length || tool.cons?.length) && (
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            {tool.pros?.length ? (
              <section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5">
                <h2 className="mb-3 text-sm font-bold text-emerald-300">{t('whatWeLiked')}</h2>
                <ul className="space-y-2">
                  {tool.pros.map((p) => (
                    <li key={p} className="flex gap-2 text-sm text-zinc-300">
                      <span aria-hidden="true" className="text-emerald-400">
                        +
                      </span>
                      {p}
                    </li>
                  ))}
                </ul>
              </section>
            ) : null}
            {tool.cons?.length ? (
              <section className="rounded-2xl border border-rose-500/20 bg-rose-500/5 p-5">
                <h2 className="mb-3 text-sm font-bold text-rose-300">{t('whatHeldItBack')}</h2>
                <ul className="space-y-2">
                  {tool.cons.map((c) => (
                    <li key={c} className="flex gap-2 text-sm text-zinc-300">
                      <span aria-hidden="true" className="text-rose-400">
                        −
                      </span>
                      {c}
                    </li>
                  ))}
                </ul>
              </section>
            ) : null}
          </div>
        )}

        {/* Description */}
        <section className="mt-8 rounded-3xl border border-white/10 bg-surface-1 p-6 sm:p-8">
          <h2 className="mb-3 text-lg font-bold">{t('whatIs', { name: tool.name })}</h2>
          {tool.pageIntro && <p className="mb-3 text-base font-semibold text-zinc-200">{tool.pageIntro}</p>}
          <p className="text-sm leading-relaxed text-zinc-300">
            {tool.longDescription ?? tool.description}
          </p>
          {tool.bestFor && (
            <p className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm text-zinc-300">
              <span className="font-bold text-emerald-300">{t('bestFor')}: </span>
              {tool.bestFor}
            </p>
          )}
          {tool.metrics && (
            <p className="mt-3 inline-flex items-center gap-2 rounded-xl border border-accent-500/20 bg-accent-500/10 px-3 py-2 text-2xs font-semibold text-accent-300">
              {t('standoutMetric')}: {tool.metrics}
            </p>
          )}
          {tool.descriptionSource && tool.verificationLevel === 'listed-only' && (
            <p className="mt-3 text-2xs text-zinc-500">
              {tool.descriptionSource}
            </p>
          )}
          <div className="mt-4 flex flex-wrap gap-1.5">
            {tool.tags.map((tag) => (
              <Link
                key={tag}
                href={`/tools?q=${encodeURIComponent(tag)}`}
                className="rounded-md border border-white/10 bg-surface-2 px-2.5 py-1 text-2xs text-zinc-400 transition-colors hover:border-accent-500/30 hover:text-accent-300"
              >
                #{tag}
              </Link>
            ))}
          </div>

          {/* Share buttons — audit fix 3.4 */}
          <div className="mt-5 border-t border-white/5 pt-4">
            <ShareButtons
              title={tool.name}
              url={`${SITE_URL}/tool/${tool.slug}`}
            />
          </div>

          {/*
            Bug fix — untested (listed-only / pricing-verified) tools carried a
            `cataloguedAt` date in the catalog and this UI showed it under the
            label "Last reviewed", implying we had actually reviewed the tool.
            We had not. Only a hands-on tested tool is "reviewed"; everything
            else is either "pricing checked" or merely "catalogued on".
          */}
          <div className="mt-3 flex flex-wrap items-center gap-3 text-2xs text-zinc-500">
            {tested && tool.testedAt && (
              <span>
                {t('lastReviewed')}:{' '}
                <time className="font-mono tabular-nums">{tool.testedAt}</time>
              </span>
            )}
            {!tested && tool.cataloguedAt && (
              <span>
                {t('cataloguedOn')}:{' '}
                <time className="font-mono tabular-nums">{tool.cataloguedAt}</time>
              </span>
            )}
            {tool.pricingCheckedAt && (
              <span>
                {t('pricingChecked')}:{' '}
                <time className="font-mono tabular-nums">{tool.pricingCheckedAt}</time>
              </span>
            )}
          </div>

          {/* Honest editorial footer — no blanket "we test everything" claim. */}
          <p className="mt-5 border-t border-white/5 pt-4 text-2xs leading-relaxed text-zinc-500">
            {tested ? (
              <>
                {tool.testedAt
                  ? t('testedByEditorial', { name: SITE_NAME, date: tool.testedAt })
                  : t('testedByEditorialShort', { name: SITE_NAME })}
                {tool.planTested ? t('usingPlan', { plan: tool.planTested }) : ''}.{' '}
              </>
            ) : (
              <>
                {t('cataloguedDisclaimer', { name: tool.name })}{' '}
              </>
            )}
            <Link href="/about" className="underline hover:text-zinc-300">
              {t('readMethodology')}
            </Link>
            .{' '}
            {tool.affiliateProgram && (
              <>
                {t('affiliateNoteShort', { name: tool.name })}{' '}
                <Link href="/disclosure" className="underline hover:text-zinc-300">
                  {t('disclosureWord')}
                </Link>
                .
              </>
            )}
          </p>
        </section>

        {/* Deep dive — hand-written for flagship tools (critique §5, §11-11). */}
        {dive && (
          <section className="mt-6 rounded-3xl border border-white/10 bg-surface-1 p-6 sm:p-8">
            <h2 className="text-lg font-bold">{t('inDepth', { name: tool.name })}</h2>
            <div className="mt-3 space-y-4">
              {dive.overview.map((para) => (
                <p key={para.slice(0, 40)} className="text-sm leading-relaxed text-zinc-300">
                  {para}
                </p>
              ))}
            </div>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <div className="rounded-2xl border border-white/10 bg-surface-2/60 p-5">
                <h3 className="text-sm font-bold text-zinc-200">{t('commonUseCases')}</h3>
                <ul className="mt-3 space-y-2">
                  {dive.useCases.map((u) => (
                    <li key={u} className="flex gap-2 text-sm text-zinc-400">
                      <span aria-hidden="true" className="text-accent-400">▸</span>
                      {u}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="space-y-4">
                <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5">
                  <h3 className="text-sm font-bold text-emerald-300">{t('bestFor')}</h3>
                  <ul className="mt-3 space-y-2">
                    {dive.bestFor.map((b) => (
                      <li key={b} className="flex gap-2 text-sm text-zinc-300">
                        <span aria-hidden="true" className="text-emerald-400">+</span>
                        {b}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="rounded-2xl border border-rose-500/20 bg-rose-500/5 p-5">
                  <h3 className="text-sm font-bold text-rose-300">{t('skipIf')}</h3>
                  <ul className="mt-3 space-y-2">
                    {dive.avoidIf.map((a) => (
                      <li key={a} className="flex gap-2 text-sm text-zinc-300">
                        <span aria-hidden="true" className="text-rose-400">−</span>
                        {a}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            {dive.pricingNotes && (
              <div className="mt-4 rounded-2xl border border-accent-500/20 bg-accent-500/5 p-5">
                <h3 className="text-sm font-bold text-accent-300">{t('pricingBehavior')}</h3>
                <p className="mt-2 text-sm leading-relaxed text-zinc-300">{dive.pricingNotes}</p>
              </div>
            )}
          </section>
        )}

        {/* FAQ — visible content + FAQPage schema (critique §7). */}
        {faqs.length > 0 && (
          <section className="mt-6">
            <h2 className="mb-4 text-xl font-bold">{t('faqTitleFor', { name: tool.name })}</h2>
            <div className="space-y-3">
              {faqs.map((f) => (
                <details
                  key={f.q}
                  className="group rounded-2xl border border-white/10 bg-surface-1 p-5 open:border-accent-500/30"
                >
                  <summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm font-bold text-zinc-100 [&::-webkit-details-marker]:hidden">
                    {f.q}
                    <span
                      aria-hidden="true"
                      className="text-accent-400 transition-transform duration-200 group-open:rotate-45"
                    >
                      +
                    </span>
                  </summary>
                  <p className="mt-3 text-sm leading-relaxed text-zinc-400">{f.a}</p>
                </details>
              ))}
            </div>
          </section>
        )}

        {replaces.length > 0 && (
          <section className="mt-6 rounded-2xl border border-white/10 bg-surface-1 p-5">
            <h2 className="text-sm font-bold text-zinc-200">{t('migratingTitle')}</h2>
            <p className="mt-2 text-sm text-zinc-400">
              {t('migratingIntro', { name: tool.name })}{' '}
              {replaces.map((d, i) => (
                <span key={d.slug}>
                  {i > 0 && ', '}
                  <Link href="/graveyard" className="text-accent-400 underline hover:text-accent-300">
                    {d.name}
                  </Link>
                </span>
              ))}
              , {t(replaces.length === 1 ? 'noLongerAvailable' : 'noLongerAvailablePlural')}.
            </p>
          </section>
        )}

        <ReviewSection toolSlug={tool.slug} toolName={tool.name} />

        {/* Micro-feedback — audit fix 3.5 */}
        <HelpfulFeedback toolSlug={tool.slug} />

        {alternatives.length > 0 && (
          <section className="mt-12">
            <h2 className="mb-1 text-xl font-bold">
              {t('topAlternatives', { name: tool.name })}
            </h2>
            <p className="mb-5 text-2xs text-zinc-500">
              {t('otherToolsWorthComparing', { category: tc.has(tool.category) ? tc(tool.category) : tool.category })}{' '}
              <Link
                href={`/alternatives/${tool.slug}`}
                className="text-accent-400 underline hover:text-accent-300"
              >
                {t('seeFullComparison')} →
              </Link>
            </p>
            <ul className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
              {alternatives.map((t, i) => (
                <li key={t.slug}>
                  <ToolCard tool={t} index={i} />
                </li>
              ))}
            </ul>
          </section>
        )}

        {related.length > 0 && (
          <section className="mt-12">
            <h2 className="mb-1 text-xl font-bold">{t('pairsWellWith')}</h2>
            <p className="mb-5 text-2xs text-zinc-500">
              {t('pairsIntro', { name: tool.name })}.
            </p>
            <ul className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
              {related.map((t, i) => (
                <li key={t.slug}>
                  <ToolCard tool={t} index={i} />
                </li>
              ))}
            </ul>
          </section>
        )}
      </main>

      <CompareBar />
      <Footer />
    </div>
  );
}
