/**
 * How much do we actually know about this tool?
 *
 * Audit fix 1.1 — the site previously rendered an identical "Evidence Card"
 * reading "Hands-on + Vendor Data / Test Date 2026-08-01" on all 200 tool
 * pages, while 153 of them were machine-generated by scripts/gen-tools.mjs
 * with reviewsCount: 0. That is a Google scaled-content-abuse pattern and an
 * FTC 16 CFR 255 deceptive-claim risk next to an affiliate link.
 *
 * Every claim the UI makes is now gated on this field:
 *  - 'hands-on-tested'   we ran the tool ourselves. Requires testedAt and
 *                        should carry evidenceUrls. Only these may show an
 *                        Evidence Card and a numeric editorial score.
 *  - 'pricing-verified'  we did not run it, but a human opened the vendor
 *                        pricing page. Requires pricingSourceUrl +
 *                        pricingCheckedAt.
 *  - 'listed-only'       catalogued from public information. No test claim,
 *                        no score. This is the honest default.
 */
export type VerificationLevel = 'hands-on-tested' | 'pricing-verified' | 'listed-only';

/**
 * Multi-dimensional editorial scoring (audit fix 2.1).
 * A single 4.1–4.9 number carried no information — no tool scored below 4.0
 * and the average was 4.46. Sub-scores are 0–10 and only ever exist on tools
 * we genuinely tested. `overall` is computed, never hand-written.
 */
export interface ToolScores {
  outputQuality: number;
  speed: number;
  valueForMoney: number;
  easeOfUse: number;
  /** Watermark-free? Commercial rights? Usable resolution? */
  exportFreedom: number;
}

export interface ToolVerdict {
  bestFor: string;
  skipIf: string;
}

/** A parsed public plan from the vendor's official pricing page. */
export interface PricingPlan {
  name: string;
  priceDisplay: string;
  billing: string;
  features?: string[];
}

export interface Tool {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  url: string;
  affiliateUrl?: string;
  /**
   * Which affiliate network the link above belongs to.
   * Audit fix 1.6 — 15 tools carried invented ?via=creatoraihub /
   * ?ref=creatoraihub parameters for programs that were never joined, so every
   * rel="sponsored" click earned nothing while the footer claimed an affiliate
   * relationship. affiliateUrl is now ignored at redirect time unless this is
   * set to a real, approved program.
   */
  affiliateProgram?: 'impact' | 'partnerstack' | 'rewardful' | 'direct' | null;
  logo: string;
  /** Local brand cover is generated by CoverArt; remote stock imagery was removed (v2.6). */
  coverImage?: string;
  category: ToolCategory;
  pricing: 'Free' | 'Freemium' | 'Paid' | 'Free Trial';
  startingPrice?: string;
  rating: number;
  reviewsCount: number;
  ratingLabel?: 'Editorial Score' | 'Community Score';
  isFeatured: boolean;
  isEditorsChoice: boolean;
  isTrending: boolean;
  isNew: boolean;
  hasFounderBadge: boolean;
  tags: string[];
  metrics?: string;
  launchDate?: string;
  cataloguedAt?: string;

  /* ---- Evidence & verification (audit fixes 1.1, 1.2, 2.1, 2.3) ---- */

  verificationLevel: VerificationLevel;
  /** ISO date of a real hands-on test. Only set for 'hands-on-tested'. */
  testedAt?: string;
  /** Screenshots, output videos, changelogs backing the review. */
  evidenceUrls?: string[];
  /** Which paid plan the test was run on, e.g. "Pro $29/mo". */
  planTested?: string;

  /* ---- Enriched editorial description (2026-08-06) ---- */
  /** Longer, platform-ready description for the tool page body. */
  longDescription?: string;
  /** One-line intro used at the top of the tool page. */
  pageIntro?: string;
  /** Short "best for" statement. */
  bestFor?: string;
  /** Capability list (richer than tags). */
  keyCapabilities?: string[];
  /** ISO date this editorial description was written. */
  descriptionUpdatedAt?: string;
  /** Who wrote it / basis (never a fabricated vendor claim). */
  descriptionSource?: string;
  /** Vendor pricing page the startingPrice was read from. */
  pricingSourceUrl?: string;
  /** ISO date the pricing was last confirmed against the vendor page. */
  pricingCheckedAt?: string;

  /* ---- Price-check evidence (2026-08-06 source crawl) ---- */

  /** How far the price check went: complete | partial | source-captured | manual. */
  priceCheckStatus?: 'complete' | 'partial' | 'source-captured' | 'source-unavailable' | 'manual';
  /** Human note on currency, billing quirks, annual-equivalent, rebrands, etc. */
  priceCheckNote?: string;
  /** Parsed public plans from the official pricing page (name, price, billing, features). */
  pricingPlans?: PricingPlan[];

  scores?: ToolScores;
  verdict?: ToolVerdict;
  /** Audit fix 2.1 — no tool on the site had a single listed drawback. */
  pros?: string[];
  cons?: string[];
}

/**
 * Shape of the raw catalog entries in tools.ts / tools-extended.ts.
 *
 * Seed data deliberately CANNOT declare its own verification level, test date
 * or scores — those are granted centrally in verified-tools.ts. This makes the
 * "we tested this" claim impossible to fake by editing a generated file.
 */
export type ToolSeed = Omit<
  Tool,
  'verificationLevel' | 'testedAt' | 'evidenceUrls' | 'planTested' | 'scores' | 'verdict' | 'pros' | 'cons'
>;

/** The evidence a hand-verified tool must supply. */
export type VerifiedRecord = Partial<Tool> & { verificationLevel: VerificationLevel };

/** Weighted overall score, 0–10, derived from sub-scores. Never hand-authored. */
export function computeOverall(s: ToolScores): number {
  const weighted =
    s.outputQuality * 0.35 +
    s.easeOfUse * 0.2 +
    s.valueForMoney * 0.2 +
    s.speed * 0.15 +
    s.exportFreedom * 0.1;
  return Math.round(weighted * 10) / 10;
}

/** True only when a numeric score is defensible to a regulator. */
export function hasVerifiedScore(t: Tool): boolean {
  return t.verificationLevel === 'hands-on-tested' && !!t.scores && !!t.testedAt;
}

export type ToolCategory =
  | 'Video Generation'
  | 'Video Editing & VFX'
  | 'Video Repurposing'
  | 'Faceless Video'
  | 'Voice & Audio'
  | 'Translation & Dubbing'
  | 'Music & SFX'
  | 'AI Avatars'
  | 'Thumbnails & Design'
  | 'Scripting & Writing'
  | 'AI Agents & Assistants'
  | 'Prompts & Templates'
  | 'Transcription & Captions'
  | 'SEO & Analytics'
  | 'Automation'
  | 'Live & Streaming'
  | '3D & Motion';

/**
 * Critique §5 fix — four missing categories added:
 * Translation & Dubbing (the biggest lever for international channel growth),
 * Faceless Video (a large sub-niche that was scattered across other groups),
 * AI Agents & Assistants (general assistants previously filed under writing)
 * and Prompts & Templates. Every category carries hand-written editorial copy
 * in src/lib/categories.ts.
 */
export const CATEGORIES = [
  'All',
  'Video Generation',
  'Video Editing & VFX',
  'Video Repurposing',
  'Faceless Video',
  'Voice & Audio',
  'Translation & Dubbing',
  'Music & SFX',
  'AI Avatars',
  'Thumbnails & Design',
  'Scripting & Writing',
  'AI Agents & Assistants',
  'Prompts & Templates',
  'Transcription & Captions',
  'SEO & Analytics',
  'Automation',
  'Live & Streaming',
  '3D & Motion',
] as const;

export type Category = typeof CATEGORIES[number];

export const PRICING_OPTIONS = ['All', 'Free', 'Freemium', 'Paid', 'Free Trial'] as const;
export type PricingOption = typeof PRICING_OPTIONS[number];


export const INITIAL_TOOLS: ToolSeed[] = [
  {
    id: '1', name: 'OpusClip', slug: 'opusclip',
    tagline: 'Turn long videos into viral shorts',
    description: 'OpusClip analyzes long-form videos using AI virality scoring to extract the highest-retention vertical clips. Auto-captions, emojis, and smart reframing included.',
    url: 'https://www.opus.pro', affiliateUrl: 'https://www.opus.pro/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=opus.pro&sz=128',
    category: 'Video Repurposing', pricing: 'Freemium', startingPrice: '$9.99/mo',
    rating: 4.9, reviewsCount: 428, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: true, isTrending: true, isNew: false, hasFounderBadge: true,
    tags: ['Shorts', 'Auto-Captions', 'Virality Score', 'YouTube to TikTok'], metrics: '10x Faster Editing', launchDate: '2022-03-15',
  },
  {
    id: '2', name: 'Munch', slug: 'munch',
    tagline: 'AI video repurposing for social media',
    description: 'Extracts the most engaging moments from long-form content using AI trend analysis and keyword virality scoring.',
    url: 'https://www.getmunch.com', affiliateUrl: 'https://www.getmunch.com/?utm_campaign=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=getmunch.com&sz=128',
    category: 'Video Repurposing', pricing: 'Paid', startingPrice: '$49/mo',
    rating: 4.6, reviewsCount: 310, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Content Repurposing', 'Podcast Clipping', 'Trend Analysis', 'TikTok'], metrics: 'AI Trend Scoring', launchDate: '2021-08-20',
  },
  {
    id: '3', name: 'Vidyo.ai', slug: 'vidyo-ai',
    tagline: 'Create short clips from long videos',
    description: 'Repurpose long podcasts and webinars into social-ready vertical clips with custom brand templates, emojis, and auto-framing.',
    url: 'https://vidyo.ai', affiliateUrl: 'https://vidyo.ai/?ref=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=vidyo.ai&sz=128',
    category: 'Video Repurposing', pricing: 'Freemium', startingPrice: '$15/mo',
    rating: 4.6, reviewsCount: 280, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Podcasts', 'Webinar Clipper', 'Brand Templates', 'Reels'], metrics: 'Custom Templates', launchDate: '2021-11-10',
  },
  {
    id: '4', name: 'Klap', slug: 'klap',
    tagline: 'Turn YouTube videos into TikToks',
    description: 'Fast AI clipping tool that identifies interesting topics in your long videos, generates vertical clips, and overlays customized captions.',
    url: 'https://klap.app', affiliateUrl: 'https://klap.app/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=klap.app&sz=128',
    category: 'Video Repurposing', pricing: 'Paid', startingPrice: '$29/mo',
    rating: 4.7, reviewsCount: 310, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['AI Clipping', 'Viral Shorts', 'Auto-Captions', 'Podcasts'], metrics: 'Fastest Clipper', launchDate: '2022-06-01',
  },
  {
    id: '5', name: 'Submagic', slug: 'submagic',
    tagline: 'Auto captions and B-roll for shorts',
    description: 'Synchronizes animated captions with your voice, inserts context-aware B-roll graphics, applies smooth camera zoom transitions, and adds subtle sound effects.',
    url: 'https://submagic.co', affiliateUrl: 'https://submagic.co?ref=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=submagic.co&sz=128',
    category: 'Video Repurposing', pricing: 'Paid', startingPrice: '$20/mo',
    rating: 4.8, reviewsCount: 298, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: false, isTrending: true, isNew: false, hasFounderBadge: true,
    tags: ['Animated Captions', 'Emojis', 'Auto Zoom', 'TikTok'], metrics: 'Alex Hormozi Captions', launchDate: '2022-09-15',
  },
  {
    id: '6', name: 'AutoShorts.ai', slug: 'autoshorts',
    tagline: 'Faceless video automation',
    description: 'Automated Short-form generator that combines GPT scripts, AI voices, and background B-roll to create faceless Shorts in seconds.',
    url: 'https://autoshorts.ai',
    logo: 'https://www.google.com/s2/favicons?domain=autoshorts.ai&sz=128',
    category: 'Faceless Video', pricing: 'Paid', startingPrice: '$19/mo',
    rating: 4.5, reviewsCount: 190, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: true, hasFounderBadge: false,
    tags: ['Faceless Shorts', 'Automated Video', 'AI Voice', 'YouTube Automation'], metrics: 'Zero-Touch Shorts', launchDate: '2023-02-01',
  },
  {
    id: '7', name: 'Pictory', slug: 'pictory',
    tagline: 'Text to video with AI voices',
    description: 'Transform scripts and articles into professional videos with AI narration, stock footage, and automatic captioning.',
    url: 'https://pictory.ai',
    logo: 'https://www.google.com/s2/favicons?domain=pictory.ai&sz=128',
    category: 'Video Repurposing', pricing: 'Freemium', startingPrice: '$19/mo',
    rating: 4.5, reviewsCount: 340, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Text to Video', 'Blog to Video', 'AI Voice', 'Auto Captions'], metrics: 'Blog to Video', launchDate: '2019-07-20',
  },
  {
    id: '8', name: 'InVideo', slug: 'invideo',
    tagline: 'AI video creation platform',
    description: 'All-in-one AI video generator that creates scripts, selects stock footage, adds subtitles, and applies realistic voiceovers from a simple text prompt.',
    url: 'https://invideo.io', affiliateUrl: 'https://invideo.io/?ref=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=invideo.io&sz=128',
    category: 'Video Repurposing', pricing: 'Freemium', startingPrice: '$15/mo',
    rating: 4.8, reviewsCount: 890, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Text to Video', 'YouTube Automation', 'Faceless Video', 'AI Scripting'], metrics: '15M+ Creators', launchDate: '2017-01-01',
  },
  {
    id: '9', name: 'Clipchamp', slug: 'clipchamp',
    tagline: "Microsoft's video editor with AI",
    description: 'Free video editor with auto-captions, text-to-speech, green screen, and speaker coach. Built by Microsoft.',
    url: 'https://clipchamp.com',
    logo: 'https://www.google.com/s2/favicons?domain=clipchamp.com&sz=128',
    category: 'Video Repurposing', pricing: 'Freemium', startingPrice: 'Free',
    rating: 4.4, reviewsCount: 1200, ratingLabel: 'Community Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Free Editor', 'Auto-Captions', 'Microsoft', 'Web-based'], metrics: '100% Free Core', launchDate: '2014-01-01',
  },
  {
    id: '10', name: 'CapCut', slug: 'capcut',
    tagline: 'All-in-one video editor',
    description: 'World-class free desktop and mobile editor with AI auto-captions, vocal isolation, background removal, and TikTok trend templates.',
    url: 'https://www.capcut.com',
    logo: 'https://www.google.com/s2/favicons?domain=capcut.com&sz=128',
    category: 'Video Repurposing', pricing: 'Free', startingPrice: 'Free',
    rating: 4.9, reviewsCount: 2100, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: false, isTrending: true, isNew: false, hasFounderBadge: false,
    tags: ['Free Editor', 'Auto-Captions', 'TikTok Editor', 'Desktop & Mobile'], metrics: '200M+ Creators', launchDate: '2020-04-01',
  },
  {
    id: '11', name: 'Runway', slug: 'runway',
    tagline: 'AI video generation and editing',
    description: 'Create cinematic AI video clips from text or reference images, remove moving objects, and apply motion tracking with Hollywood-grade AI.',
    url: 'https://runwayml.com',
    logo: 'https://www.google.com/s2/favicons?domain=runwayml.com&sz=128',
    category: 'Video Generation', pricing: 'Paid', startingPrice: '$15/mo',
    rating: 4.9, reviewsCount: 410, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: true, isTrending: true, isNew: false, hasFounderBadge: false,
    tags: ['Text to Video', 'Gen-3 Alpha', 'Inpainting', 'VFX'], metrics: 'Hollywood VFX', launchDate: '2018-01-01',
  },
  {
    id: '12', name: 'Descript', slug: 'descript',
    tagline: 'Edit video by editing text',
    description: 'All-in-one video and podcast editor with AI overdub, studio sound enhancement, filler word removal, and automatic transcription.',
    url: 'https://www.descript.com', affiliateUrl: 'https://www.descript.com?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=descript.com&sz=128',
    category: 'Video Editing & VFX', pricing: 'Freemium', startingPrice: '$12/mo',
    rating: 4.8, reviewsCount: 520, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: true, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Text-Based Editing', 'Studio Sound', 'Filler Removal', 'Podcasting'], metrics: 'Studio Quality AI', launchDate: '2017-01-01',
  },
  {
    id: '13', name: 'Filmora', slug: 'filmora',
    tagline: 'Easy video editor with AI',
    description: 'Beginner-friendly video editor with AI copilot, smart cutout, motion tracking, and thousands of effects and templates.',
    url: 'https://filmora.wondershare.com',
    logo: 'https://www.google.com/s2/favicons?domain=filmora.wondershare.com&sz=128',
    category: 'Video Editing & VFX', pricing: 'Paid', startingPrice: '$49.99/yr',
    rating: 4.5, reviewsCount: 850, ratingLabel: 'Community Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Beginner Friendly', 'AI Copilot', 'Templates', 'Motion Tracking'], metrics: 'Easy Learning Curve', launchDate: '2015-01-01',
  },
  {
    id: '14', name: 'VEED', slug: 'veed',
    tagline: 'Online video editor with AI',
    description: 'Professional browser-based video editing platform with one-click subtitle translation, filler word removal, and instant resizing for social channels.',
    url: 'https://www.veed.io', affiliateUrl: 'https://www.veed.io/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=veed.io&sz=128',
    category: 'Video Editing & VFX', pricing: 'Freemium', startingPrice: '$12/mo',
    rating: 4.7, reviewsCount: 650, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Online Editor', 'Auto Subtitles', 'Screen Recording', 'TikTok'], metrics: 'In-Browser Editing', launchDate: '2018-01-01',
  },
  {
    id: '15', name: 'Adobe Premiere Pro', slug: 'adobe-premiere-pro',
    tagline: 'Professional video editing',
    description: 'Industry-standard professional video editor with AI-powered color matching, scene edit detection, speech-to-text, and seamless After Effects integration.',
    url: 'https://www.adobe.com/products/premiere.html',
    logo: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128',
    category: 'Video Editing & VFX', pricing: 'Paid', startingPrice: '$22.99/mo',
    rating: 4.8, reviewsCount: 3200, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Professional', 'Color Grading', 'After Effects', 'Industry Standard'], metrics: 'Industry Standard', launchDate: '1991-12-01',
  },
  {
    id: '16', name: 'DaVinci Resolve', slug: 'davinci-resolve',
    tagline: 'Professional color grading',
    description: 'Hollywood-grade color correction, Fairlight audio, Fusion VFX, and Cut page editing — completely free for the standard version.',
    url: 'https://www.blackmagicdesign.com/products/davinciresolve',
    logo: 'https://www.google.com/s2/favicons?domain=blackmagicdesign.com&sz=128',
    category: 'Video Editing & VFX', pricing: 'Free', startingPrice: 'Free',
    rating: 4.9, reviewsCount: 1800, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: true, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Color Grading', 'Free', 'Hollywood', 'VFX'], metrics: 'Hollywood Grade', launchDate: '2004-01-01',
  },
  {
    id: '17', name: 'Final Cut Pro', slug: 'final-cut-pro',
    tagline: "Apple's professional editor",
    description: "Apple's professional video editing software with magnetic timeline, 360° VR, HDR, and advanced color grading optimized for Apple Silicon.",
    url: 'https://www.apple.com/final-cut-pro/',
    logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=128',
    category: 'Video Editing & VFX', pricing: 'Paid', startingPrice: '$299 one-time',
    rating: 4.8, reviewsCount: 950, ratingLabel: 'Community Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Apple', 'Magnetic Timeline', 'HDR', 'ProRes'], metrics: 'Apple Optimized', launchDate: '2011-06-21',
  },
  {
    id: '18', name: 'Synthesia', slug: 'synthesia',
    tagline: 'AI video generation with avatars',
    description: 'Create professional videos with AI avatars in 130+ languages. No camera, studio, or actors needed. Perfect for training and corporate content.',
    url: 'https://www.synthesia.io',
    logo: 'https://www.google.com/s2/favicons?domain=synthesia.io&sz=128',
    category: 'AI Avatars', pricing: 'Paid', startingPrice: '$22/mo',
    rating: 4.7, reviewsCount: 680, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['AI Avatars', 'Corporate', '130+ Languages', 'Training'], metrics: '130+ Languages', launchDate: '2017-01-01',
  },
  {
    id: '19', name: 'HeyGen', slug: 'heygen',
    tagline: 'AI avatars and video translation',
    description: 'Create AI avatar videos with lip-sync translation in 40+ languages. Clone your voice and appearance for scalable personalized video content.',
    url: 'https://www.heygen.com', affiliateUrl: 'https://www.heygen.com/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=heygen.com&sz=128',
    category: 'AI Avatars', pricing: 'Paid', startingPrice: '$24/mo',
    rating: 4.8, reviewsCount: 520, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: false, isTrending: true, isNew: false, hasFounderBadge: true,
    tags: ['AI Avatars', 'Lip Sync', 'Translation', 'Personalization'], metrics: '40+ Languages', launchDate: '2020-01-01',
  },
  {
    id: '20', name: 'D-ID', slug: 'd-id',
    tagline: 'AI video creation with talking photos',
    description: 'Transform photos into realistic talking head videos. Integrates with ChatGPT for interactive AI presenters and conversational agents.',
    url: 'https://www.d-id.com',
    logo: 'https://www.google.com/s2/favicons?domain=d-id.com&sz=128',
    category: 'AI Avatars', pricing: 'Paid', startingPrice: '$5.9/mo',
    rating: 4.5, reviewsCount: 380, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Talking Photos', 'ChatGPT', 'Interactive', 'API'], metrics: 'Photo to Video', launchDate: '2017-01-01',
  },
  {
    id: '21', name: 'ElevenLabs', slug: 'elevenlabs',
    tagline: 'Most realistic AI voice cloning',
    description: 'The industry standard for AI voiceovers, voice cloning, and dubbing in 29+ languages. Perfect for faceless YouTube channels and documentaries.',
    url: 'https://elevenlabs.io', affiliateUrl: 'https://elevenlabs.io/?from=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128',
    category: 'Voice & Audio', pricing: 'Freemium', startingPrice: '$5/mo',
    rating: 4.9, reviewsCount: 612, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: true, isTrending: true, isNew: false, hasFounderBadge: true,
    tags: ['Voice Cloning', 'Text to Speech', 'Multilingual', 'Audio'], metrics: '29+ Languages', launchDate: '2022-01-01',
  },
  {
    id: '22', name: 'Murf.ai', slug: 'murf-ai',
    tagline: 'AI voiceovers for videos',
    description: 'Versatile AI voice generator offering over 120+ realistic voices in 20 languages. Includes pitch control, emphasis editing, and background music syncing.',
    url: 'https://murf.ai', affiliateUrl: 'https://murf.ai/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=murf.ai&sz=128',
    category: 'Voice & Audio', pricing: 'Freemium', startingPrice: '$19/mo',
    rating: 4.7, reviewsCount: 510, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['AI Voiceover', 'Explainer Videos', '120+ Voices', 'Pitch Control'], metrics: '120+ Human Voices', launchDate: '2020-01-01',
  },
  {
    id: '24', name: 'Descript Overdub', slug: 'descript-overdub',
    tagline: 'Clone your voice with AI',
    description: 'Create a text-to-speech model of your own voice. Edit audio by editing text. Fix mistakes in recordings without re-recording.',
    url: 'https://www.descript.com/overdub',
    logo: 'https://www.google.com/s2/favicons?domain=descript.com&sz=128',
    category: 'Voice & Audio', pricing: 'Freemium', startingPrice: '$12/mo',
    rating: 4.6, reviewsCount: 280, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Voice Cloning', 'Overdub', 'Podcast Editing', 'Text to Speech'], metrics: 'Your Own Voice', launchDate: '2019-01-01',
  },
  {
    id: '25', name: 'Resemble AI', slug: 'resemble-ai',
    tagline: 'Real-time voice cloning',
    description: 'Real-time voice cloning API with emotion control, localization, and deepfake detection. Enterprise-grade security and compliance.',
    url: 'https://www.resemble.ai',
    logo: 'https://www.google.com/s2/favicons?domain=resemble.ai&sz=128',
    category: 'Voice & Audio', pricing: 'Paid', startingPrice: '$0.006/sec',
    rating: 4.5, reviewsCount: 220, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Real-time', 'API', 'Emotion Control', 'Enterprise'], metrics: 'Real-Time Clone', launchDate: '2019-01-01',
  },
  {
    id: '26', name: 'Lovo.ai', slug: 'lovo-ai',
    tagline: 'AI voice generator for creators',
    description: 'All-in-one voiceover and video creator platform featuring emotional speech control, sound effects library, and multi-speaker dialog editing.',
    url: 'https://lovo.ai', affiliateUrl: 'https://lovo.ai/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=lovo.ai&sz=128',
    category: 'Voice & Audio', pricing: 'Freemium', startingPrice: '$19/mo',
    rating: 4.6, reviewsCount: 320, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Emotional Voices', 'Dialog Editor', 'Video Dubbing', '500+ Voices'], metrics: '500+ AI Voices', launchDate: '2019-01-01',
  },
  {
    id: '27', name: 'Adobe Podcast', slug: 'adobe-podcast',
    tagline: 'AI audio enhancement',
    description: 'Free AI speech enhancement that removes background noise and echoes from any microphone recording instantly.',
    url: 'https://podcast.adobe.com/enhance',
    logo: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128',
    category: 'Voice & Audio', pricing: 'Free', startingPrice: 'Free',
    rating: 4.9, reviewsCount: 880, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Noise Removal', 'Audio Enhancement', 'Free Tool', 'Studio Speech'], metrics: '100% Free Tool', launchDate: '2022-01-01',
  },
  {
    id: '28', name: 'Auphonic', slug: 'auphonic',
    tagline: 'Automatic audio post-production',
    description: 'Automatic audio post-production web service for podcasts, broadcasters, and video creators. Leveler, noise reduction, and loudness normalization.',
    url: 'https://auphonic.com',
    logo: 'https://www.google.com/s2/favicons?domain=auphonic.com&sz=128',
    category: 'Voice & Audio', pricing: 'Freemium', startingPrice: '$11/mo',
    rating: 4.6, reviewsCount: 290, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Audio Post-Production', 'Leveler', 'Loudness', 'Podcast'], metrics: 'Auto Leveling', launchDate: '2012-01-01',
  },
  {
    id: '29', name: 'Krisp', slug: 'krisp',
    tagline: 'AI noise cancellation',
    description: 'AI-powered noise cancellation for calls and recordings. Removes background voices, barking dogs, and keyboard clicks in real-time.',
    url: 'https://krisp.ai',
    logo: 'https://www.google.com/s2/favicons?domain=krisp.ai&sz=128',
    category: 'Voice & Audio', pricing: 'Freemium', startingPrice: '$8/mo',
    rating: 4.7, reviewsCount: 410, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Noise Cancellation', 'Real-time', 'Calls', 'Recording'], metrics: 'Real-Time Clean', launchDate: '2017-01-01',
  },
  {
    id: '30', name: 'Cleanvoice', slug: 'cleanvoice',
    tagline: 'AI audio cleaning',
    description: 'Automatically removes filler words, mouth sounds, stuttering, and dead air from podcast and video recordings.',
    url: 'https://cleanvoice.ai',
    logo: 'https://www.google.com/s2/favicons?domain=cleanvoice.ai&sz=128',
    category: 'Voice & Audio', pricing: 'Paid', startingPrice: '$10/mo',
    rating: 4.5, reviewsCount: 180, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: true, hasFounderBadge: true,
    tags: ['Filler Removal', 'Mouth Sounds', 'Dead Air', 'Podcast'], metrics: 'Auto Clean', launchDate: '2021-01-01',
  },
  {
    id: '34', name: 'Colossyan', slug: 'colossyan',
    tagline: 'AI video generation for training',
    description: 'Create training videos with AI presenters in minutes. Auto-translate to 70+ languages with localized accents.',
    url: 'https://www.colossyan.com',
    logo: 'https://www.google.com/s2/favicons?domain=colossyan.com&sz=128',
    category: 'AI Avatars', pricing: 'Paid', startingPrice: '$28/mo',
    rating: 4.6, reviewsCount: 240, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Training', '70+ Languages', 'Auto-Translate', 'Enterprise'], metrics: '70+ Languages', launchDate: '2020-01-01',
  },
  {
    id: '35', name: 'Elai.io', slug: 'elai-io',
    tagline: 'AI video creation with avatars',
    description: 'Build customized AI videos with digital presenters from text. 80+ languages, 25+ avatars, and PPT-to-video conversion.',
    url: 'https://elai.io',
    logo: 'https://www.google.com/s2/favicons?domain=elai.io&sz=128',
    category: 'AI Avatars', pricing: 'Paid', startingPrice: '$23/mo',
    rating: 4.5, reviewsCount: 190, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['PPT to Video', '80+ Languages', 'Digital Presenter', 'Text to Video'], metrics: 'PPT to Video', launchDate: '2021-01-01',
  },
  {
    id: '37', name: 'Canva', slug: 'canva',
    tagline: 'Design anything with AI',
    description: 'All-in-one design platform with AI Magic Write, background remover, and thousands of templates for thumbnails, banners, and social posts.',
    url: 'https://www.canva.com',
    logo: 'https://www.google.com/s2/favicons?domain=canva.com&sz=128',
    category: 'Thumbnails & Design', pricing: 'Freemium', startingPrice: '$12.99/mo',
    rating: 4.9, reviewsCount: 4500, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: true, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Thumbnails', 'AI Write', 'Templates', 'Social Posts'], metrics: '135M+ Users', launchDate: '2012-01-01',
  },
  {
    id: '38', name: 'Adobe Express', slug: 'adobe-express',
    tagline: 'Quick and easy design',
    description: 'Create thumbnails, flyers, and social posts with AI generative fill, text effects, and thousands of professionally designed templates.',
    url: 'https://www.adobe.com/express',
    logo: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128',
    category: 'Thumbnails & Design', pricing: 'Freemium', startingPrice: '$9.99/mo',
    rating: 4.6, reviewsCount: 780, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Generative Fill', 'Templates', 'Quick Design', 'Adobe'], metrics: 'Adobe Powered', launchDate: '2015-01-01',
  },
  {
    id: '39', name: 'Thumbly.ai', slug: 'thumbly-ai',
    tagline: 'AI YouTube thumbnail generator',
    description: 'Generate high-CTR YouTube thumbnails using AI trained on viral video data. Face detection, emotion analysis, and color psychology built-in.',
    url: 'https://thumbly.ai',
    logo: 'https://www.google.com/s2/favicons?domain=thumbly.ai&sz=128',
    category: 'Thumbnails & Design', pricing: 'Paid', startingPrice: '$19/mo',
    rating: 4.5, reviewsCount: 210, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: true, isNew: true, hasFounderBadge: true,
    tags: ['YouTube Thumbnails', 'CTR', 'AI Generated', 'Viral Data'], metrics: 'High CTR AI', launchDate: '2023-01-01',
  },
  {
    id: '40', name: 'Snappa', slug: 'snappa',
    tagline: 'Graphic design for non-designers',
    description: 'Create YouTube thumbnails, channel art, and social media graphics in minutes with pre-made templates and stock photos.',
    url: 'https://snappa.com',
    logo: 'https://www.google.com/s2/favicons?domain=snappa.com&sz=128',
    category: 'Thumbnails & Design', pricing: 'Freemium', startingPrice: '$10/mo',
    rating: 4.4, reviewsCount: 340, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Non-Designer', 'Templates', 'Stock Photos', 'YouTube Art'], metrics: '5M+ Graphics', launchDate: '2015-01-01',
  },
  {
    id: '41', name: 'Jasper', slug: 'jasper',
    tagline: 'AI writing assistant',
    description: "AI copywriter trained for marketing. Write video scripts, blog posts, ad copy, and social captions with brand voice consistency.",
    url: 'https://www.jasper.ai',
    logo: 'https://www.google.com/s2/favicons?domain=jasper.ai&sz=128',
    category: 'Scripting & Writing', pricing: 'Paid', startingPrice: '$39/mo',
    rating: 4.6, reviewsCount: 520, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Video Scripts', 'Brand Voice', 'Marketing', 'Blog Posts'], metrics: 'Marketing Focused', launchDate: '2021-01-01',
  },
  {
    id: '42', name: 'Copy.ai', slug: 'copy-ai',
    tagline: 'AI copywriting for marketers',
    description: 'Generate marketing copy, video hooks, ad scripts, and email sequences in seconds. 90+ templates and workflows included.',
    url: 'https://www.copy.ai',
    logo: 'https://www.google.com/s2/favicons?domain=copy.ai&sz=128',
    category: 'Scripting & Writing', pricing: 'Freemium', startingPrice: '$36/mo',
    rating: 4.5, reviewsCount: 480, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Copywriting', 'Video Hooks', 'Ad Scripts', 'Workflows'], metrics: '90+ Templates', launchDate: '2020-01-01',
  },
  {
    id: '43', name: 'ChatGPT', slug: 'chatgpt',
    tagline: 'General-purpose AI assistant',
    description: "OpenAI's conversational AI for brainstorming, script writing, research, and code generation. The swiss army knife for creators.",
    url: 'https://chat.openai.com',
    logo: 'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
    category: 'AI Agents & Assistants', pricing: 'Freemium', startingPrice: '$20/mo',
    rating: 4.9, reviewsCount: 5000, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: false, isTrending: true, isNew: false, hasFounderBadge: false,
    tags: ['Brainstorming', 'Script Writing', 'Research', 'Code'], metrics: '100M+ Users', launchDate: '2022-11-30',
  },
  {
    id: '44', name: 'Claude', slug: 'claude',
    tagline: 'Advanced AI writing and analysis',
    description: "Anthropic's AI assistant with industry-leading context window. Perfect for long-form script analysis, research synthesis, and creative writing.",
    url: 'https://claude.ai',
    logo: 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
    category: 'AI Agents & Assistants', pricing: 'Freemium', startingPrice: '$20/mo',
    rating: 4.8, reviewsCount: 1200, ratingLabel: 'Editorial Score',
    isFeatured: true, isEditorsChoice: true, isTrending: true, isNew: false, hasFounderBadge: false,
    tags: ['Long Context', 'Analysis', 'Creative Writing', 'Research'], metrics: '200K Context', launchDate: '2023-03-14',
  },
  {
    id: '45', name: 'Writesonic', slug: 'writesonic',
    tagline: 'AI content creation',
    description: 'AI writer with SEO optimization, paraphrasing, and image generation. Create blog posts, landing pages, and video scripts that rank.',
    url: 'https://writesonic.com',
    logo: 'https://www.google.com/s2/favicons?domain=writesonic.com&sz=128',
    category: 'Scripting & Writing', pricing: 'Freemium', startingPrice: '$13/mo',
    rating: 4.4, reviewsCount: 360, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['SEO', 'Paraphrasing', 'Image Gen', 'Blog Posts'], metrics: 'SEO Optimized', launchDate: '2021-01-01',
  },
  {
    id: '46', name: 'Zapier', slug: 'zapier',
    tagline: 'Automate workflows with AI',
    description: 'Connect 5000+ apps to automate your creator workflow. Auto-publish videos, send notifications, and sync data across platforms.',
    url: 'https://zapier.com',
    logo: 'https://www.google.com/s2/favicons?domain=zapier.com&sz=128',
    category: 'Automation', pricing: 'Freemium', startingPrice: '$19.99/mo',
    rating: 4.7, reviewsCount: 2100, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['5000+ Apps', 'Auto-Publish', 'Workflows', 'Integrations'], metrics: '5000+ Integrations', launchDate: '2011-01-01',
  },
  {
    id: '47', name: 'Make', slug: 'make',
    tagline: 'Visual automation platform',
    description: 'Visual no-code automation with drag-and-drop scenario builder. More powerful and visual than Zapier for complex creator workflows.',
    url: 'https://www.make.com',
    logo: 'https://www.google.com/s2/favicons?domain=make.com&sz=128',
    category: 'Automation', pricing: 'Freemium', startingPrice: '$9/mo',
    rating: 4.6, reviewsCount: 680, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['Visual Builder', 'No-Code', 'Scenarios', 'Complex Logic'], metrics: 'Visual Scenarios', launchDate: '2012-01-01',
  },
  {
    id: '48', name: 'n8n', slug: 'n8n',
    tagline: 'Open-source workflow automation',
    description: 'Self-hostable open-source automation with 400+ integrations. Full control over your data. Perfect for privacy-conscious creators.',
    url: 'https://n8n.io',
    logo: 'https://www.google.com/s2/favicons?domain=n8n.io&sz=128',
    category: 'Automation', pricing: 'Freemium', startingPrice: '$20/mo',
    rating: 4.7, reviewsCount: 520, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: true, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Open Source', 'Self-Hosted', '400+ Integrations', 'Privacy'], metrics: 'Open Source', launchDate: '2019-01-01',
  },
  {
    id: '49', name: 'Repurpose.io', slug: 'repurpose-io',
    tagline: 'Auto-publish content everywhere',
    description: 'Automatically repurpose and distribute your videos and audio to all major platforms. Set it once, publish everywhere forever.',
    url: 'https://repurpose.io',
    logo: 'https://www.google.com/s2/favicons?domain=repurpose.io&sz=128',
    category: 'Automation', pricing: 'Paid', startingPrice: '$15/mo',
    rating: 4.5, reviewsCount: 290, ratingLabel: 'Editorial Score',
    isFeatured: false, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: true,
    tags: ['Auto-Publish', 'Distribution', 'Podcast', 'YouTube'], metrics: 'Publish Everywhere', launchDate: '2016-01-01',
  },
  {
    id: '50', name: 'TubeBuddy', slug: 'tubebuddy',
    tagline: 'YouTube growth and optimization',
    description: 'Browser extension for YouTube SEO, A/B testing thumbnails, bulk processing, and advanced analytics. Essential for serious YouTubers.',
    url: 'https://www.tubebuddy.com', affiliateUrl: 'https://www.tubebuddy.com/?via=creatoraihub',
    logo: 'https://www.google.com/s2/favicons?domain=tubebuddy.com&sz=128',
    category: 'Automation', pricing: 'Freemium', startingPrice: '$4.50/mo',
    rating: 4.6, reviewsCount: 1800, ratingLabel: 'Community Score',
    isFeatured: true, isEditorsChoice: false, isTrending: false, isNew: false, hasFounderBadge: false,
    tags: ['YouTube SEO', 'A/B Testing', 'Bulk Processing', 'Analytics'], metrics: 'YouTube Certified', launchDate: '2014-01-01',
  },
];

// ---- Merge in the extended curated dataset (150+ tools) ----
import { EXTENDED_TOOLS } from './tools-extended';
import { DEAD_TOOL_SLUGS } from './graveyard';
import { VERIFIED_TOOLS } from './verified-tools';
import { TOOL_DESCRIPTIONS } from './descriptions';

/**
 * Audit fix 1.1 / 1.2.
 *
 * Nothing in the raw seed arrays carries a verification claim. This is the
 * single place where verification is applied, and it only ever grants a level
 * above 'listed-only' when there is a matching hand-authored record in
 * verified-tools.ts. It is deliberately impossible to earn an Evidence Card by
 * editing a machine-generated file.
 */
function applyVerification(t: ToolSeed): Tool {
  const verified = VERIFIED_TOOLS[t.slug];
  // Editorial descriptions are granted centrally too (never trusted from the
  // machine-generated seed file), exactly like verification level.
  const desc = TOOL_DESCRIPTIONS[t.slug];

  const base = {
    ...t,
    ...desc,
  };

  if (!verified) {
    // Honest default: catalogued, not tested. No numeric score is surfaced,
    // and reviewsCount is trusted only when it came from a real source.
    return {
      ...base,
      verificationLevel: 'listed-only',
      cataloguedAt: t.cataloguedAt ?? undefined,
      testedAt: undefined,
      scores: undefined,
    };
  }

  return {
    ...base,
    ...verified,
    verificationLevel: verified.verificationLevel,
  };
}

/** The complete, deduplicated tool catalog used across the whole site. */
export const ALL_TOOLS: Tool[] = (() => {
  const seen = new Set<string>();
  const merged: Tool[] = [];
  for (const seed of [...INITIAL_TOOLS, ...EXTENDED_TOOLS]) {
    // Audit fix 1.5 — Play.ht, Hour One and Morningfame are confirmed dead
    // (DNS does not resolve / server never answers). They now live in the
    // graveyard with a migration path instead of sending users to a timeout.
    if (DEAD_TOOL_SLUGS.has(seed.slug)) continue;
    if (seen.has(seed.slug)) continue;
    seen.add(seed.slug);
    merged.push(applyVerification(seed));
  }
  return merged;
})();

/** Tools we genuinely ran ourselves — the only ones allowed an Evidence Card. */
export const TESTED_TOOLS: Tool[] = ALL_TOOLS.filter(hasVerifiedScore);

export const UNIQUE_TOOLS = ALL_TOOLS;
export const getFeaturedTools = () => ALL_TOOLS.filter((t) => t.isFeatured);
export const getToolsByCategory = (category: Category) =>
  category === 'All' ? ALL_TOOLS : ALL_TOOLS.filter((t) => t.category === category);
export const searchTools = (query: string) => {
  const q = query.toLowerCase();
  return ALL_TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.tagline.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
  );
};
export const filterByPricing = (tools: Tool[], pricing: PricingOption) =>
  pricing === 'All' ? tools : tools.filter((t) => t.pricing === pricing);
