'use client';
/* eslint-disable jsx-a11y/label-has-associated-control */
import { useMemo, useState } from 'react';
import { Check, Copy, RefreshCcw, Sparkles } from 'lucide-react';
import { StudioSelect } from './StudioSelect';


const initial = { output: 'Image', topic: '', audience: '', style: 'Cinematic and clear', platform: 'YouTube', ratio: '16:9', required: '', avoid: '' };
const fieldClass = 'studio-field';
function CopyButton({ value }: { value: string }) { const [copied, setCopied] = useState(false); return <button className="studio-copy" onClick={async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }} aria-label="Copy output">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />} {copied ? 'Copied' : 'Copy'}</button>; }

export function PromptBuilder() {
 const [form, setForm] = useState(initial); const [made, setMade] = useState(false);
 const update = (key: keyof typeof initial, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
 const prompts = useMemo(() => { const subject = form.topic.trim() || '[your subject]'; const audience = form.audience.trim() || '[your audience]'; const required = form.required.trim() ? ` Include: ${form.required.trim()}.` : ''; const avoid = form.avoid.trim() ? ` Avoid: ${form.avoid.trim()}.` : ''; const base = `${form.output} for ${form.platform}, ${form.ratio} format, about ${subject}, made for ${audience}, ${form.style.toLowerCase()}.${required}`; return { short: `${form.output}: ${subject}. ${form.style}. ${form.ratio}.${avoid}`, standard: base + avoid, detailed: `Create a polished ${form.output.toLowerCase()} for ${form.platform} in ${form.ratio}. Core subject: ${subject}. Audience: ${audience}. Visual and editorial direction: ${form.style}. Keep the main message immediately understandable, use purposeful composition and a clear focal point.${required}${avoid}`, negative: form.output === 'Script' ? 'Avoid unsupported facts, fabricated results, vague filler, and claims that cannot be substantiated.' : `Avoid clutter, unreadable text, distorted anatomy, ambiguous focal points, watermarks, logos, and off-brief elements.${form.avoid ? ` Also avoid: ${form.avoid}.` : ''}` }; }, [form]);
 return <div className="mx-auto grid max-w-7xl gap-6 px-4 pb-20 sm:px-6 lg:grid-cols-[.86fr_1.14fr]"><form className="studio-form-card" onSubmit={(e) => { e.preventDefault(); setMade(true); }}><div className="flex items-center justify-between"><h2>Build your brief</h2><button type="button" className="studio-reset" onClick={() => { setForm(initial); setMade(false); }}><RefreshCcw className="h-3.5 w-3.5" /> Reset</button></div><label>Output type<StudioSelect ariaLabel="Output type" value={form.output} onChange={(value) => update('output', value)} options={['Image','Video','Thumbnail','Script','Avatar','B-roll'].map((value) => ({ value, label: value }))} /></label><label>Main subject or message<textarea className={fieldClass} required value={form.topic} onChange={(e)=>update('topic',e.target.value)} placeholder="e.g. A creator explaining how they grew a cooking channel" /></label><label>Audience<textarea className={fieldClass} value={form.audience} onChange={(e)=>update('audience',e.target.value)} placeholder="e.g. New food creators who publish weekly" /></label><div className="grid grid-cols-2 gap-3"><label>Style / tone<input className={fieldClass} value={form.style} onChange={(e)=>update('style',e.target.value)} /></label><label>Platform<StudioSelect ariaLabel="Platform" value={form.platform} onChange={(value)=>update('platform',value)} options={['YouTube','TikTok','Instagram','LinkedIn','Generic'].map((value)=>({value,label:value}))} /></label></div><label>Aspect ratio<StudioSelect ariaLabel="Aspect ratio" value={form.ratio} onChange={(value)=>update('ratio',value)} options={['16:9','9:16','1:1','4:5'].map((value)=>({value,label:value}))} /></label><label>Must include <input className={fieldClass} value={form.required} onChange={(e)=>update('required',e.target.value)} placeholder="Optional" /></label><label>Do not include <input className={fieldClass} value={form.avoid} onChange={(e)=>update('avoid',e.target.value)} placeholder="Optional" /></label><button className="studio-generate" type="submit"><Sparkles className="h-4 w-4" /> Generate prompt set</button></form><section className="studio-results" aria-live="polite"><div className="studio-results-heading"><div><p className="studio-eyebrow">Output</p><h2>{made ? 'Prompt set ready' : 'Your structured prompts will appear here'}</h2></div><span>{made ? 'Rule-based · local' : 'No model call'}</span></div>{made ? <div className="space-y-4">{Object.entries(prompts).map(([name,value])=><article className="studio-output" key={name}><div className="flex items-center justify-between gap-4"><h3>{name === 'short' ? 'Short prompt' : name === 'standard' ? 'Standard prompt' : name === 'detailed' ? 'Detailed prompt' : 'Negative prompt'}</h3><CopyButton value={value} /></div><p>{value}</p></article>)}</div> : <div className="studio-empty"><Sparkles className="h-7 w-7" /><p>Fill in your creative direction, then generate a reusable prompt in the browser.</p></div>}</section></div>;
}
