'use client';
/* eslint-disable jsx-a11y/label-has-associated-control */
import { useMemo, useState } from 'react';
import { Check, Copy, Sparkles } from 'lucide-react';
import { StudioSelect } from './StudioSelect';
type Group = 'Hook'|'Curiosity'|'Result'|'Comparison'|'Urgency';
const starters: Record<Group,string[]> = {Hook:['THE REAL','STOP DOING','THIS CHANGED','I FINALLY FOUND'],Curiosity:['WHAT HAPPENS WHEN','THE PART NOBODY SEES','WHY THIS WORKS','THE HIDDEN'],Result:['FROM IDEA TO','A CLEARER','THE SIMPLE WAY TO','MADE FOR'],Comparison:['OLD WAY vs NEW','BEFORE / AFTER','HUMAN OR AI?','THIS vs THAT'],Urgency:['DON’T WASTE','BEFORE YOU','FIX THIS FIRST','START HERE']};
function trimWords(value:string,max:number){return value.split(/\s+/).filter(Boolean).slice(0,max).join(' ')}
export function ThumbnailTextGenerator(){const[f,setF]=useState({topic:'',type:'Tutorial',tone:'Clear',max:4});const[ready,setReady]=useState(false);const options=useMemo(()=>{const topic=trimWords(f.topic||'YOUR NEXT VIDEO',Math.max(1,f.max-1)).toUpperCase();const suffix=f.type==='Comparison'?'?':f.type==='Tutorial'?' NOW':'';return (Object.keys(starters) as Group[]).flatMap(group=>starters[group].slice(0,3).map((starter,index)=>{let text=index===0?`${starter} ${topic}`:index===1?`${topic}${suffix}`:`${starter} ${topic}`;text=trimWords(text,f.max);return{group,text,words:text.split(' ').length};}));},[f]); const copy=async (value:string)=>navigator.clipboard.writeText(value);return <div className="mx-auto grid max-w-7xl gap-6 px-4 pb-20 sm:px-6 lg:grid-cols-[.72fr_1.28fr]"><form className="studio-form-card" onSubmit={e=>{e.preventDefault();setReady(true)}}><h2>Set the constraint</h2><label>Topic<textarea className="studio-field" required value={f.topic} onChange={e=>setF({...f,topic:e.target.value})} placeholder="e.g. editing a podcast in one hour"/></label><label>Content type<StudioSelect ariaLabel="Content type" value={f.type} onChange={value=>setF({...f,type:value})} options={['Tutorial','Review','Challenge','News','Story','Comparison','Reaction'].map((value)=>({value,label:value}))} /></label><label>Tone<StudioSelect ariaLabel="Tone" value={f.tone} onChange={value=>setF({...f,tone:value})} options={['Clear','Confident','Playful','Direct','Calm'].map((value)=>({value,label:value}))} /></label><label>Maximum words <span className="studio-range-value">{f.max}</span><input className="studio-range" type="range" min="2" max="6" value={f.max} onChange={e=>setF({...f,max:Number(e.target.value)})}/></label><button className="studio-generate"><Sparkles className="h-4 w-4"/> Generate 15 options</button><p className="studio-help">Templates use your topic; they do not invent results, numbers, or claims.</p></form><section className="studio-results" aria-live="polite"><div className="studio-results-heading"><div><p className="studio-eyebrow">Short copy</p><h2>{ready?'15 honest starting points':'Keep it short, legible, and truthful'}</h2></div><span>{ready?'15 options':'2–6 words'}</span></div>{ready?<div className="studio-text-grid">{options.map((item,i)=><article className="studio-text-option" key={`${item.group}-${i}`}><div><span>{item.group}</span><small>{item.words} words</small></div><strong>{item.text}</strong><button onClick={()=>copy(item.text)} aria-label={`Copy ${item.text}`}><Copy className="h-4 w-4"/></button></article>)}</div>:<div className="studio-empty"><Check className="h-7 w-7"/><p>Good thumbnail copy reinforces a real promise. It should never replace a truthful title with a misleading claim.</p></div>}</section></div>}
